[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = ["OnchainBackup"]
show_progress = true
fs_permissions = [{ access = "read-write", path = "./"}]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.2"
